# Generated by Django 4.0.3 on 2022-06-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteshoe',
            name='flightClub',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='favoriteshoe',
            name='goat',
            field=models.CharField(max_length=300),
        ),
    ]
