# Generated by Django 4.0.3 on 2022-06-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers_app', '0004_remove_favoriteshoe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteshoe',
            name='image',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
