# Generated by Django 4.0.3 on 2022-06-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers_app', '0007_remove_favoriteshoe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteshoe',
            name='releaseDate',
            field=models.DateField(blank=True),
        ),
    ]
